script:
    echo "Only script"

before_install:
    echo "Before install"
    echo $TRAVIS_TEST_RESULT

before_script:
    echo "Before script"

after_script:
    echo "After script"

after_success:
    echo "After success"

after_failure:
    ehco "After failure"