script:
    echo "Script running..."

before_install:
    - echo "Before install 1"
    - echo "Before install 2"
    - sudo apt-get update

before_script:
    echo "Before script"

after_script:
    echo "After script"

after_success:
    echo "After success"

after_failure:
    echo "After failure"

install: ./install-dependencies.sh

notifications:
  email:
    - vinothg.cdm@gmail.com